@baseUrl=http://localhost:3000/api
@resourceName=activities
@userId=1
@taskId=2
@name=Julian Herbst

# @name login
GET http://localhost:3000/login

###
# @name getUserData
GET {{baseUrl}}/users

###
# @name getDataTableAndPagination
GET {{baseUrl}}/activities?_page=1

###
# @name sortDataTable
GET {{baseUrl}}/activities?_sort=amount&_order=asc

###
# @name getChartData
GET {{baseUrl}}/charts

###
# @name getPost&CommentData
GET {{baseUrl}}/posts

###
# @name addComment
POST {{baseUrl}}/posts
Content-Type: application/json

{
    "name": "Kathryn Murphy" , //current username
    "comment": "Love FA training"
}

###
# @name getTasksByUserId
// other endpoint: GET {{baseUrl}}/tasks?userId={{userId}}&monthId=10
GET {{baseUrl}}/users/{{userId}}/tasks


###
# @name addNewTask
POST {{baseUrl}}/tasks
Content-Type: application/json

{
   "content": "Workshop IDND",
    "status": "doing",
    "dateId": 1,  // date
    "monthId": 10, // month
    "userId": 1 // current user id
}

###
# @name updateTask
PATCH {{baseUrl}}/tasks/{{taskId}}
Content-Type: application/json

{
    "content": "Townhall Meeting",
    "status": "pending",
}

###
# @name deleteTask
DELETE {{baseUrl}}/tasks/{{taskId}}
