@baseUrl=http://localhost:3000/api
@resourceName=products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###
# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?color=olive&price_gte=200

###
# @name filterProductsLike
GET {{baseUrl}}/{{resourceName}}?name_like=unbra

###
# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1


###
# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=asc

###
# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "categoryId": "821d463a-ef25-435f-8a2c-f6a83c035f29",
    "name": "Small Fresh Gloves",
    "color": "fuchsia",
    "price": 1752,
    "description": "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    "thumbnailUrl": "http://placeimg.com/400/400"
}

###
PATCH  {{baseUrl}}/{{resourceName}}/o_HoXT5
Content-Type: application/json

{
    "name": "Small Fresh",
    "color": "red",
    "price": 100
}


###
DELETE   {{baseUrl}}/{{resourceName}}/2
